### POST request to example server

POST https://1adf-37-61-114-117.ngrok-free.app/auth/telegram
Content-Type: application/json

{
  "id": "4",
  "auth_date": "1685000000",
  "first_name": "Ramazan",
  "username": "ramazan_bot",
  "hash": "ВАШ_ХЭШ_ТУТ"
}


###